// <auto-generated />
using System;
using Airline;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace S3.Migrations
{
    [DbContext(typeof(AirlineContext))]
    partial class AirlineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Airline.Entity.AirLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contact_Person")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("Airline.Entity.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AL_Id")
                        .HasColumnType("int");

                    b.Property<string>("Assistant")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Host1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Host2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Maj_pilot")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AL_Id");

                    b.ToTable("Aircrafts");
                });

            modelBuilder.Entity("Airline.Entity.Airline_Phone", b =>
                {
                    b.Property<int>("AL_Id")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(2);

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.HasKey("AL_Id", "Phone");

                    b.HasIndex("AirlineId");

                    b.ToTable("Airline_Phones");
                });

            modelBuilder.Entity("Airline.Entity.Emp_Qualification", b =>
                {
                    b.Property<int>("Emp_Id")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Qualification")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(2);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Emp_Id", "Qualification");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Emp_Qualifications");
                });

            modelBuilder.Entity("Airline.Entity.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AL_Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BD_Day")
                        .HasColumnType("int");

                    b.Property<int>("BD_Month")
                        .HasColumnType("int");

                    b.Property<int>("BD_Year")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AL_Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Airline.Entity.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Airline.Entity.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AL_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AL_Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("S3.Entity.Crew", b =>
                {
                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<string>("Assis_Pilot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CrewMaj_Pilot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Host1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Host2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AircraftId");

                    b.ToTable("Aircrafts", null, t =>
                        {
                            t.Property("Host1")
                                .HasColumnName("Crew_Host1");

                            t.Property("Host2")
                                .HasColumnName("Crew_Host2");
                        });
                });

            modelBuilder.Entity("S3.Entity.FlightAssignment", b =>
                {
                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Num_Of_Passengers")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AircraftId", "RouteId");

                    b.HasIndex("RouteId");

                    b.ToTable("FlightAssignments");
                });

            modelBuilder.Entity("Airline.Entity.Aircraft", b =>
                {
                    b.HasOne("Airline.Entity.AirLine", "Airline")
                        .WithMany("Aircrafts")
                        .HasForeignKey("AL_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Airline.Entity.Airline_Phone", b =>
                {
                    b.HasOne("Airline.Entity.AirLine", "Airline")
                        .WithMany("Phones")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Airline.Entity.Emp_Qualification", b =>
                {
                    b.HasOne("Airline.Entity.Employee", "emp")
                        .WithMany("Qualifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("emp");
                });

            modelBuilder.Entity("Airline.Entity.Employee", b =>
                {
                    b.HasOne("Airline.Entity.AirLine", "Airline")
                        .WithMany("Employees")
                        .HasForeignKey("AL_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Airline.Entity.Transaction", b =>
                {
                    b.HasOne("Airline.Entity.AirLine", "Airline")
                        .WithMany("Transactions")
                        .HasForeignKey("AL_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("S3.Entity.Crew", b =>
                {
                    b.HasOne("Airline.Entity.Aircraft", "Aircraft")
                        .WithOne("Crew")
                        .HasForeignKey("S3.Entity.Crew", "AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("S3.Entity.FlightAssignment", b =>
                {
                    b.HasOne("Airline.Entity.Aircraft", "Aircraft")
                        .WithMany("FlightAssignments")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Airline.Entity.Route", "Route")
                        .WithMany("FlightAssignments")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Airline.Entity.AirLine", b =>
                {
                    b.Navigation("Aircrafts");

                    b.Navigation("Employees");

                    b.Navigation("Phones");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Airline.Entity.Aircraft", b =>
                {
                    b.Navigation("Crew")
                        .IsRequired();

                    b.Navigation("FlightAssignments");
                });

            modelBuilder.Entity("Airline.Entity.Employee", b =>
                {
                    b.Navigation("Qualifications");
                });

            modelBuilder.Entity("Airline.Entity.Route", b =>
                {
                    b.Navigation("FlightAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
