// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentA;

#nullable disable

namespace Payment.Migrations
{
    [DbContext(typeof(PaymentContext))]
    partial class PaymentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaymentA.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Payments");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PaymentA.Models.CashPayment", b =>
                {
                    b.HasBaseType("PaymentA.Models.Payment");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CashPayments", (string)null);
                });

            modelBuilder.Entity("PaymentA.Models.CreditCardPayment", b =>
                {
                    b.HasBaseType("PaymentA.Models.Payment");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CreditCardPayments", (string)null);
                });

            modelBuilder.Entity("PaymentA.Models.CashPayment", b =>
                {
                    b.HasOne("PaymentA.Models.Payment", null)
                        .WithOne()
                        .HasForeignKey("PaymentA.Models.CashPayment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PaymentA.Models.CreditCardPayment", b =>
                {
                    b.HasOne("PaymentA.Models.Payment", null)
                        .WithOne()
                        .HasForeignKey("PaymentA.Models.CreditCardPayment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
